name:                calculator
version:             0.1.0.0
github:              "githubuser/calculator"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- containers
- haskeline
- parsec
- checkers
- QuickCheck

library:
  source-dirs: src

executables:
  calculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calculator
    - parsec
    - checkers
    - containers
    - QuickCheck
    - hspec

tests:
  calculator-hspec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - calculator
    - hspec
    - QuickCheck
    - hlint-test
  calculator-hlint-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calculator
    - hspec
    - QuickCheck
    - hlint
    - hlint-test
